### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by simon-grantham** [mParticle/mparticle-roku-sdk#11]
Lines starting at 103 of mParticleCore have equal signs instead of colons.  Should read:

    MEDIA_STREAM_TYPE = {
        LIVE_STREAM: "LiveStream",
        ON_DEMAND: "OnDemand",
        LINEAR: "Linear",
        PODCAST: "Podcast",
        AUDIOBOOK: "Audiobook"
    }

**Comment by BrandonStalnaker** [comment]
Thank you for your response. Looking into it now.

**Comment by BrandonStalnaker** [comment]
Fixed with https://github.com/mParticle/mparticle-roku-sdk/commit/d87f881cde1157d06a0acd7abc1e2c0019984f8f
