### ISSUE TITLE
Deprecated Function for Certification

### ISSUE THREAD

**Issue by DanielWAdam** [mParticle/mparticle-roku-sdk#19]
As per Roku documentation:

> The GetVersion() API has been deprecated. Use the roDeviceInfo.GetOsVersion() function instead, which was introduced in Roku 9.2 OS, to get the major, minor, revision, and build numbers of the Roku OS running on a device.

There are two instances of this function still being called in mParticleCore.brs. The line numbers are 934 and 967.

**Comment by samdozor** [comment]
@DanielWAdam thanks for logging the issue - assigning to @BrandonStalnaker
